### ISSUE TITLE
Confusing duplication

### ISSUE THREAD

**Issue by wbeckler** [eliatra/opensearch-k8s-operator#1]
It looks like Opster's github project now redirects to one hosted by OpenSearch, which makes this one redundant:
https://github.com/Opster/opensearch-k8s-operator

**Comment by salyh** [comment]
--- No longer maintained ---

This repo is no longer maintained and outdated. Please use the offical OpenSearch operator https://github.com/opensearch-project/opensearch-k8s-operator

See also https://opensearch.org/blog/launching-open-source-operator-for-openSearch/
